using System.Collections.Generic;
using UnityEngine;
#if ENABLE_INPUT_SYSTEM
using UnityEngine.InputSystem;
#endif
using WorldEvolution; // TimeOfDayWeather, CharacterDefinition, ...

// WorldEvolution namespace is for the project's own types
// (TimeOfDayWeather, CharacterDefinition, ...).

/// <summary>
/// GTA V-style third-person controller for the billboarded caveman — SMOOTH edition.
///
/// What makes it feel 3-dimensional instead of "flipping paper cut-outs":
///  1. CONTINUOUS DIRECTION CROSS-FADE — the exact camera↔character angle maps to a
///     floating direction index (e.g. 4.37). The shader cross-fades between the two
///     neighbouring direction sprites, so orbiting the camera morphs smoothly
///     through every in-between angle instead of snapping between 8/16 sprites.
///  2. TURN GLIDE — the floating index is time-smoothed, so when the player changes
///     direction the character visibly glides through the in-between poses.
///  3. ORBIT LEAN — while the camera orbits or the character turns, the quad leans
///     a few degrees into the motion, faking rotational inertia/mass.
///  4. LIVING IDLE — the shader (Game/BillboardBlendWind) animates hair sway,
///     loincloth flutter and breathing on the GPU, driven by generated sway masks.
///     This script adds eased HEAD GLANCES — the head region cross-fades
///     toward the neighbouring direction view (a real head turn using the
///     artist's own pixels) — plus natural eye blinks; all perfectly smooth.
///
/// Setup: add this INSTEAD of PlayerController3D + IdleAnimator, assign the 16
/// direction sprites (and optionally the 16 sway masks), and give the
/// SpriteRenderer the "Game/BillboardBlendWind" material. The material is
/// instanced automatically per character, so every caveman can have its own
/// wind phase / tint.
/// </summary>
[DefaultExecutionOrder(10)] // after ThirdPersonCamera so the billboard uses the final camera pose
public class BillboardCharacter : MonoBehaviour
{
    [Header("Sprites — turntable order")]
    [Tooltip("Front, then rotating around the character (00_front, 01_front_right_slight, ... 15_front_left_slight).\n" +
             "All sprites MUST be the same pixel size and NOT packed into a sprite atlas.")]
    public Sprite[] directionSprites;

    [Header("Sway masks (same order as sprites)")]
    [Tooltip("R = hair, G = cloth/loincloth, B = torso/breathing. Generated by tools/generate_sway_masks.py.\n" +
             "Import them as plain textures (default import settings) and leave this empty to auto-load\n" +
             "them from Resources/CharacterMasks/<sprite name>_mask. Without masks a procedural fallback is used.")]
    public Texture2D[] directionMasks;

    [Tooltip("If directionMasks is empty, try Resources/CharacterMasks/<sprite name>_mask automatically.")]
    public bool autoLoadMasksFromResources = true;

    [Header("Movement")]
    public float moveSpeed = 5f;
    public float stopDistance = 0.15f;
    public bool clickToMove = true;

    [Header("Direction blending")]
    [Tooltip("Seconds the direction takes to glide when the camera orbits / he turns. 0 = snap instantly to the nearest of the 16 sprites (no ghost, no cross-fade). 0.10-0.20 = smooth turn glide.")]
    public float turnSmoothTime = 0.0f;

    [Tooltip("How sharply the two neighbouring direction sprites cross-fade. Not used when turnSmoothTime is 0.")]
    [Range(0f, 1f)] public float blendSharpness = 1.0f;

    [Tooltip("Keep the silhouette fully opaque while two views cross-fade (prevents the see-through/blurry frame).")]
    public bool solidSilhouetteWhileBlending = true;

    [Tooltip("Tick if he faces the wrong way when strafing left/right.")]
    public bool mirrorLeftRight = false;

    [Tooltip("If true, the character rotates to face the movement direction. " +
             "If false (default, safer), the character always faces the camera so the " +
             "sprite can never be seen edge-on. WASD still works — it just changes " +
             "WHICH direction sprite is shown, not the rotation of the quad.")]
    public bool characterFacesMovement = false;

    [Header("Orbit lean (fake rotational inertia)")]
    [Tooltip("Degrees the sprite leans while the camera orbits or he turns. 0 = off. " +
             "Recommended 0 for turntable-style 16-dir characters — lean here causes " +
             "sprite flicker at the round-half-to-even seam.")]
    public float orbitLeanDegrees = 0f;
    public float leanSmoothing = 6f;
    public bool invertLean = false;

    [Header("Wind")]
    [Tooltip("World XZ direction the breeze blows towards.")]
    public Vector2 windDirection = new Vector2(1f, 0.25f);

    [Tooltip("Global wind strength (scales hair + cloth sway).")]
    public float windStrength = 1f;

    public float windSpeed = 1.6f;

    [Tooltip("Hair sway amplitude in pixels (relative to the sprite width).")]
    public float hairSwayPixels = 3.0f;

    [Tooltip("Loincloth flutter amplitude in pixels. 0 = bottom cloth stays still (default).\nRaise to ~3.6 if you want the hem to flutter in the breeze again.")]
    public float clothFlutterPixels = 0f;

    [Header("Breathing / idle life")]
    [Tooltip("Breaths per second. 0.22 ≈ 13 breaths/min.")]
    public float breathsPerSecond = 0.235f;

    [Range(0f, 2f)] public float breathAmount = 1.0f;
    [Range(0f, 3f)] public float idleBodyBob = 1.0f;

    [Header("Head + eyes")]
    [Tooltip("How strongly the head glances left/right while idle. 0 = still head, 1 = default.")]
    [Range(0f, 2f)] public float headLookAmount = 0.6f;

    [Tooltip("How far the head turns when glancing, as a fraction of one direction step (0.85 ≈ 19°, a natural glance).")]
    [Range(0.2f, 1f)] public float headLookMaxBlend = 0.5f;

    [Tooltip("Blink naturally while idle.")]
    public bool blink = true;
    [Tooltip("Minimum seconds between blinks (humans blink every ~3-6 seconds).")]
    [Range(0.5f, 10f)] public float blinkMinDelay = 2.5f;
    [Tooltip("Maximum seconds between blinks.")]
    [Range(0.5f, 10f)] public float blinkMaxDelay = 4.5f;
    [Tooltip("Chance to blink twice in a row.")]
    [Range(0f, 1f)] public float doubleBlinkChance = 0.15f;

    [Header("Hands")]
    [Tooltip("Slow fist clench (finger curl) amount. 0 = off.")]
    [Range(0f, 2f)] public float fingerCurlAmount = 1f;

    [Header("Walking")]
    [Range(0f, 3f)] public float walkBobAmount = 1f;
    [Tooltip("Stride cycles per second at full speed.")]
    public float strideRate = 1.4f;

    [Header("Contact shadow")]
    [Tooltip("Soft dark blob under his feet (drawn by the shader). 0 = off.")]
    [Range(0f, 1f)] public float contactShadowStrength = 0.38f;

    [Header("Green-screen cleanup")]
    [Tooltip("Cut leftover keyed-green fringe. Driven every frame so an old material cannot leave the shader toggle off.")]
    public bool cutTransparentGreenEdges = true;
    [Range(0f, 0.5f)] public float transparentEdgeCutoff = 0.10f;

    [Header("Environment (day / night / rain / dark)")]
    [Tooltip("Subscribes to the global TimeOfDay/Weather system at runtime; you can also drive these by hand for cinematics.")]
    [Range(0f, 2f)] public float daylight = 1.0f;
    [Tooltip("Multiplicative RGB tint applied to the whole sprite. Use (1,1,1) for normal, a cool blue for night, etc.")]
    public Color ambientTint = Color.white;
    [Range(0f, 1f)] public float wetness = 0f;
    [Tooltip("Tiny highlight shimmer on wet hair / cloth. Set to 0 for a clean matte look.")]
    [Range(0f, 0.5f)] public float wetShine = 0.18f;
    [Range(0f, 1f)] public float darkness = 0f;
    [Tooltip("If true, the character follows the global TimeOfDay/Weather singleton (created on demand).")]
    public bool followGlobalEnvironment = true;

    [Header("Misc")]
    [Tooltip("Randomize wind/breath phase so multiple characters don't animate in sync.")]
    public bool randomPhasePerInstance = true;

    // ---------------- public state (handy for other scripts) ----------------
    /// <summary>World-space facing direction.</summary>
    public Vector3 Facing { get; private set; } = Vector3.forward;

    /// <summary>Continuous direction index, e.g. 4.37 = 37% between sprite 4 and 5.</summary>
    public float ContinuousDirection => contDir;

    /// <summary>Nearest discrete direction index (compatibility with old scripts).</summary>
    public int CurrentDirectionIndex => ((int)contDir) % DirCount;

    /// <summary>True while the character is moving.</summary>
    public bool IsMoving { get; private set; }

    // ---------------- internals ----------------
    static readonly int ID_TexB          = Shader.PropertyToID("_TexB");
    static readonly int ID_MaskA         = Shader.PropertyToID("_MaskA");
    static readonly int ID_MaskB         = Shader.PropertyToID("_MaskB");
    static readonly int ID_Blend         = Shader.PropertyToID("_Blend");
    static readonly int ID_BlendSharp    = Shader.PropertyToID("_BlendSharp");
    static readonly int ID_BlendUnion    = Shader.PropertyToID("_BlendAlphaUnion");
    static readonly int ID_WindDirX      = Shader.PropertyToID("_WindDirX");
    static readonly int ID_WindSpeed     = Shader.PropertyToID("_WindSpeed");
    static readonly int ID_HairAmp       = Shader.PropertyToID("_HairAmp");
    static readonly int ID_ClothAmp      = Shader.PropertyToID("_ClothAmp");
    static readonly int ID_HeadGlance   = Shader.PropertyToID("_HeadGlance");
    static readonly int ID_TexHead      = Shader.PropertyToID("_TexHead");
    static readonly int ID_Blink         = Shader.PropertyToID("_Blink");
    static readonly int ID_ClenchAmp     = Shader.PropertyToID("_ClenchAmp");
    static readonly int ID_BreathRate    = Shader.PropertyToID("_BreathRate");
    static readonly int ID_BreathAmp     = Shader.PropertyToID("_BreathAmp");
    static readonly int ID_BobAmp        = Shader.PropertyToID("_BobAmp");
    static readonly int ID_MoveBlend     = Shader.PropertyToID("_MoveBlend");
    static readonly int ID_MovePhase     = Shader.PropertyToID("_MovePhase");
    static readonly int ID_StrideAmp     = Shader.PropertyToID("_StrideAmp");
    static readonly int ID_ShadowStr     = Shader.PropertyToID("_ShadowStrength");
    static readonly int ID_TexSize       = Shader.PropertyToID("_TexSize");
    static readonly int ID_BodyCentreX   = Shader.PropertyToID("_BodyCentreX");
    static readonly int ID_Phase         = Shader.PropertyToID("_Phase");
    static readonly int ID_FallbackMask  = Shader.PropertyToID("_FallbackMask");
    static readonly int ID_AlphaClip     = Shader.PropertyToID("_AlphaClip");
    static readonly int ID_AlphaClipThr  = Shader.PropertyToID("_AlphaClipThreshold");
    static readonly int ID_Daylight      = Shader.PropertyToID("_Daylight");
    static readonly int ID_AmbientTint   = Shader.PropertyToID("_AmbientTint");
    static readonly int ID_Wetness       = Shader.PropertyToID("_Wetness");
    static readonly int ID_WetShine      = Shader.PropertyToID("_WetShine");
    static readonly int ID_Darkness      = Shader.PropertyToID("_Darkness");

    // Textures already scanned for green key spill this session (avoids
    // running GetPixels32 again on every Awake).
    static readonly HashSet<int> greenCheckedTextures = new HashSet<int>();

    SpriteRenderer sr;
    Material mat;
    Vector3? moveTarget;
    Vector3 moveDir;
    float contDir;          // smoothed continuous direction index
    float contDirVel;       // SmoothDamp velocity
    int dirA = -1;          // which sprite is currently bound to _MainTex
    float lean;             // current orbit-lean (degrees)
    float prevRelAngle;     // for angular velocity
    float moveBlend;        // 0 idle .. 1 full speed (smoothed)
    float moveBlendVel;
    float movePhase;        // stride cycle
    Texture2D[] masks;      // resolved masks (may be null entries)
    bool usingFallbackMask;

    // blink state machine
    float nextBlinkAt;
    int blinkStage;         // 0 idle, 1 closing, 2 opening
    float blinkTimer;
    float blinkAmount;      // 0 open .. 1 closed
    bool queuedDoubleBlink;

    // head-glance state machine (looking left / right a little)
    float glanceAngle;      // current head turn, degrees (+ = one side, - = other)
    float glanceFrom, glanceTo, glanceT, glanceDur;
    float nextGlanceAt;
    int glanceStage;        // 0 holding, 1 turning
    int lastLookSide;       // +/- 1, so glances mostly alternate

    int DirCount => directionSprites == null ? 0 : directionSprites.Length;

    // ------------------------------------------------------------------ setup
    void Awake()
    {
        sr = GetComponent<SpriteRenderer>();
        if (sr == null)
        {
            Debug.LogError("BillboardCharacter: no SpriteRenderer on this object.", this);
            enabled = false;
            return;
        }
        if (DirCount < 2)
        {
            Debug.LogError("BillboardCharacter: assign at least 2 direction sprites.", this);
            enabled = false;
            return;
        }
        for (int i = 0; i < directionSprites.Length; i++)
        {
            if (directionSprites[i] == null)
                Debug.LogError($"BillboardCharacter: directionSprites[{i}] is null.", this);
            else if (directionSprites[i].packed)
                Debug.LogError("BillboardCharacter: sprites are packed into a SpriteAtlas — " +
                               "the blend shader needs standalone textures. Remove them from the atlas.", this);
        }

        // instance the material so each character can have its own wind phase
        mat = sr.material;
        if (!mat.shader.name.Contains("BillboardBlendWind"))
            Debug.LogWarning("BillboardCharacter: the SpriteRenderer's material does not use the " +
                             "Game/BillboardBlendWind shader — smooth blending and wind will not show. " +
                             "Create a material from BillboardBlendWind.shader and assign it.", this);

        ResolveMasks();
        ForceClampWrap();
        WarnIfSpritesStillHaveGreenKey();

        // Preserve the direction the object was authored with until the first
        // movement input.  This matters when the camera uses that initial
        // facing to place itself behind the player; leaving Facing at the
        // hard-coded +Z default makes a rotated player begin in a side view.
        Vector3 initialFacing = transform.forward;
        initialFacing.y = 0f;
        if (initialFacing.sqrMagnitude > 0.001f)
            Facing = initialFacing.normalized;

        contDir = DirCount * 0.5f;                 // start facing away from the camera (back view)
        BindDirection(DirCount / 2, true);
        prevRelAngle = 180f;

        mat.SetFloat(ID_Phase, randomPhasePerInstance ? Random.value * 100f : 0f);
        mat.SetFloat(ID_WindSpeed, windSpeed);
        mat.SetFloat(ID_BreathRate, breathsPerSecond);
        mat.SetFloat(ID_BreathAmp, breathAmount);
        mat.SetFloat(ID_BobAmp, idleBodyBob);
        mat.SetFloat(ID_ClenchAmp, fingerCurlAmount);
        mat.SetFloat(ID_Daylight, daylight);
        mat.SetColor(ID_AmbientTint, ambientTint);
        mat.SetFloat(ID_Wetness, wetness);
        mat.SetFloat(ID_WetShine, wetShine);
        mat.SetFloat(ID_Darkness, darkness);
        mat.SetFloat(ID_AlphaClip, cutTransparentGreenEdges ? 1f : 0f);
        mat.SetFloat(ID_AlphaClipThr, transparentEdgeCutoff);
        glanceStage = 0;
        glanceAngle = 0f;
        nextGlanceAt = Time.time + Random.Range(0.6f, 1.8f);
        lastLookSide = Random.value < 0.5f ? -1 : 1;
        nextBlinkAt = Time.time + Random.Range(blinkMinDelay, blinkMaxDelay);
        mat.SetFloat(ID_StrideAmp, walkBobAmount);
        mat.SetFloat(ID_ShadowStr, contactShadowStrength);
        mat.SetFloat(ID_FallbackMask, usingFallbackMask ? 1f : 0f);

        var t0 = directionSprites[0];
        if (t0 != null && t0.texture != null)
            mat.SetVector(ID_TexSize, new Vector4(t0.texture.width, t0.texture.height, 0, 0));
    }

    void ResolveMasks()
    {
        masks = directionMasks;
        if ((masks == null || masks.Length == 0) && autoLoadMasksFromResources)
        {
            var loaded = new List<Texture2D>(DirCount);
            for (int i = 0; i < DirCount; i++)
            {
                Sprite s = directionSprites[i];
                Texture2D m = s != null
                    ? Resources.Load<Texture2D>($"CharacterMasks/{s.name}_mask")
                    : null;
                loaded.Add(m);
            }
            masks = loaded.ToArray();
        }

        int have = 0;
        if (masks != null)
            for (int i = 0; i < masks.Length; i++)
                if (masks[i] != null) have++;

        usingFallbackMask = have == 0;
        if (have > 0 && have < DirCount)
            Debug.LogWarning($"BillboardCharacter: only {have}/{DirCount} sway masks assigned — " +
                             "missing directions will not sway. (Masks: tools/generate_sway_masks.py)", this);
    }

    void ForceClampWrap()
    {
        // Repeat wrap on a green-keyed sprite turns UV displacement (hair/breath)
        // into a lime streak from the opposite edge of the texture.
        for (int i = 0; i < DirCount; i++)
        {
            Sprite s = directionSprites[i];
            if (s != null && s.texture != null)
                s.texture.wrapMode = TextureWrapMode.Clamp;
        }
        if (masks == null) return;
        for (int i = 0; i < masks.Length; i++)
            if (masks[i] != null)
                masks[i].wrapMode = TextureWrapMode.Clamp;
    }

    /// <summary>
    /// The shipped sprites are re-keyed (they contain ZERO green-dominant
    /// pixels). If the assigned sprites still contain green key pixels, the
    /// project is using outdated PNGs — the old ones have a soft lime fringe
    /// that renders as the green streaks. Say exactly that on the console
    /// instead of rendering silently.
    /// </summary>
    void WarnIfSpritesStillHaveGreenKey()
    {
        if (directionSprites == null) return;
        bool anyBad = false;
        int scanned = 0;
        for (int i = 0; i < directionSprites.Length && scanned < 4; i++)
        {
            Sprite s = directionSprites[i];
            if (s == null || s.texture == null) continue;
            if (!greenCheckedTextures.Add(s.texture.GetInstanceID())) continue;
            scanned++;

            // Imported PNGs are not readable on the CPU by default. We
            // silently skip the green-key check in that case — the
            // current shipped sprites have no green pixels anyway, so
            // skipping the check never causes a regression. We do not
            // log a warning because the noise drowns the console.
            if (!s.texture.isReadable) continue;

            try
            {
                Color32[] px = s.texture.GetPixels32();
                int green = 0;
                for (int j = 0; j < px.Length; j++)
                {
                    Color32 p = px[j];
                    if (p.a > 2 && p.g - Mathf.Max(p.r, p.b) > 4) green++;
                }

                if (green > 0)
                {
                    anyBad = true;
                    Debug.LogError(
                        $"{name}: sprite '{s.name}' still contains {green} green screen-key pixels " +
                        "— you are using the OLD sprite PNGs (they were re-keyed; current PNGs have zero green). " +
                        "Copy the current sprites_16 / sprites_16_idle PNGs and both shaders over the Assets copies, " +
                        "then Assets > Reimport All and recreate the material from the current shader.",
                        this);
                }
            }
            catch (System.Exception e)
            {
                Debug.LogWarning($"{name}: could not scan '{s.name}' for green key pixels ({e.Message}).", this);
            }
        }

        if (anyBad)
            Debug.LogError(
                $"{name}: green streaks are caused by outdated sprite textures — see Unity_Smooth_Billboard_Setup.md > Troubleshooting.",
                this);
    }

    // ------------------------------------------------------------------ update
    void Update()
    {
        moveDir = Vector3.zero;

        float h = 0f, v = 0f;
#if ENABLE_INPUT_SYSTEM
        Keyboard kb = Keyboard.current;
        if (kb != null)
        {
            if (kb.wKey.isPressed || kb.upArrowKey.isPressed)    v += 1f;
            if (kb.sKey.isPressed || kb.downArrowKey.isPressed)  v -= 1f;
            if (kb.dKey.isPressed || kb.rightArrowKey.isPressed) h += 1f;
            if (kb.aKey.isPressed || kb.leftArrowKey.isPressed)  h -= 1f;
        }
        Gamepad pad = Gamepad.current;
        if (pad != null)
        {
            Vector2 st = pad.leftStick.ReadValue();
            // Use a small deadzone, then clamp to -1/+1 so that a half-
            // pushed stick does NOT turn the character halfway. The user
            // is on a 2.5D turntable — turns are always 90 degrees and
            // fully on/off.
            float sx = Mathf.Abs(st.x) > 0.15f ? Mathf.Sign(st.x) : 0f;
            float sy = Mathf.Abs(st.y) > 0.15f ? Mathf.Sign(st.y) : 0f;
            h += sx;
            v += sy;
        }
#else
        h = Input.GetAxisRaw("Horizontal");
        v = Input.GetAxisRaw("Vertical");
        // Clamp the legacy input axes to -1 / 0 / +1 for the same reason:
        // a half-pushed stick should not half-turn the character.
        h = Mathf.Abs(h) > 0.5f ? Mathf.Sign(h) : 0f;
        v = Mathf.Abs(v) > 0.5f ? Mathf.Sign(v) : 0f;
#endif

        // The 2.5D-RPG controls below match what a player expects from a
        // top-down / over-the-shoulder sprite game (Stardew, Pokemon,
        // Diablo). All keys are mapped to 8 strict directions and the
        // character's Facing is set to the direction of travel:
        //
        //   W  alone -> walk AWAY from camera, face away (back sprite)
        //   S  alone -> walk TOWARD camera, face camera (front sprite)
        //   A  alone -> turn 90° LEFT and walk in that new direction
        //   D  alone -> turn 90° RIGHT and walk in that new direction
        //
        //   AW -> walk NW (45 deg off camera) -> 3/4 back-left sprite
        //   WD -> walk NE (45 deg off camera) -> 3/4 back-right sprite
        //   AS -> walk SW (45 deg off camera) -> 3/4 front-left sprite
        //   SD -> walk SE (45 deg off camera) -> 3/4 front-right sprite
        //
        //   AD / WS  -> contradictory; IGNORED entirely (no turn, no walk)
        //
        // The character's FACE (mouth) always points in the direction of
        // travel, so the sprite INDEX picks the correct view automatically.
        if (Mathf.Abs(h) > 0.01f || Mathf.Abs(v) > 0.01f)
        {
            moveTarget = null;
            Camera cam = Camera.main;
            Vector3 f = cam ? cam.transform.forward : Vector3.forward; f.y = 0f; f.Normalize();
            Vector3 r = cam ? cam.transform.right   : Vector3.right;    r.y = 0f; r.Normalize();

            // Map keys to a 2D stick vector in camera-relative space.
            float stickX = 0f, stickY = 0f;
            if (h < -0.5f) stickX -= 1f;          // A
            else if (h > 0.5f) stickX += 1f;       // D
            if (v > 0.5f) stickY += 1f;            // W
            else if (v < -0.5f) stickY -= 1f;     // S

            // Detect contradictory inputs. AD and WS press at the same
            // time both cancel each other (e.g. A pushes left, D pushes
            // right; the net is zero, the character should not move or
            // half-turn).
            //   WS = forward + backward = no walk
            //   AD = left + right       = no walk, no turn
            if (stickX != 0f && stickY != 0f)
            {
                // diagonal — walk in the stick direction
                moveDir = f * stickY + r * stickX;
                Facing = moveDir.normalized;
            }
            else if (stickY > 0.01f)
            {
                // W alone — walk AWAY from camera, back to camera
                moveDir = f;
                Facing = moveDir.normalized;
            }
            else if (stickY < -0.01f)
            {
                // S alone — walk TOWARD camera, face camera
                moveDir = -f;
                Facing = moveDir.normalized;
            }
            else if (stickX > 0.01f)
            {
                // D alone — walk RIGHT (camera-right, world east).
                // Turn 90° clockwise (Quaternion.Euler(0, -90, 0)
                // rotates (0,0,1) to (1,0,0)) and then walk in that
                // new direction. The user asked for A and D to WALK
                // (not just turn in place), so moveDir matches the
                // new Facing and the character strides sideways
                // while the body faces the direction of travel.
                float turn = -90f;
                Vector3 newFacing = Quaternion.Euler(0f, turn, 0f) * f;
                Facing = newFacing.normalized;
                moveDir = Facing;
            }
            else if (stickX < -0.01f)
            {
                // A alone — walk LEFT (camera-left, world west).
                // Turn 90° counter-clockwise (Quaternion.Euler(0,
                // +90, 0) rotates (0,0,1) to (-1,0,0)) and then
                // walk in that new direction. The body faces the
                // direction of travel, the sprite is the LEFT-side
                // view, and the character strides laterally.
                float turn = 90f;
                Vector3 newFacing = Quaternion.Euler(0f, turn, 0f) * f;
                Facing = newFacing.normalized;
                moveDir = Facing;
            }
            // else: both stickX and stickY are 0 (AD or WS press) — do
            // nothing, leave Facing and moveDir alone.
        }
        else if (clickToMove && MouseLeftClicked())
        {
            TrySetMoveTarget();
        }

        if (moveTarget.HasValue)
        {
            Vector3 to = moveTarget.Value - transform.position;
            to.y = 0f;
            if (to.magnitude <= stopDistance) moveTarget = null;
            else moveDir = to.normalized;
        }

        bool moving = moveDir.sqrMagnitude > 0.001f;
        IsMoving = moving;
        if (moving)
        {
            // Same speed for W (away) and S (toward) so the player can
            // pace the character identically in both directions — the
            // user asked for W speed and S speed to be the same.
            // (The earlier "backward is slower" was a safety hack to
            // keep the character out of the camera, but the camera is
            // now properly framed, so the hack is no longer needed.)
            transform.position += moveDir * moveSpeed * Time.deltaTime;
        }

        UpdateBlink();
        UpdateHeadLook();

        // smoothed move blend + stride phase for the walk bob
        float targetBlend = moving ? 1f : 0f;
        moveBlend = Mathf.SmoothDamp(moveBlend, targetBlend, ref moveBlendVel, 0.18f);
        if (moving) movePhase += Time.deltaTime * strideRate * (moveSpeed > 0f ? 1f : 0f);
        movePhase = Mathf.Repeat(movePhase, 1f);
    }

    /// <summary>
    /// Natural idle head GLANCES: the head eases to a small look angle, holds
    /// it briefly, and eases back — like a person idly looking left and right.
    /// Every turn uses smootherstep easing (zero velocity AND acceleration at
    /// both ends), so the motion is perfectly smooth by construction: no
    /// wobble, no drift, no per-frame randomness while turning.
    /// </summary>
    void UpdateHeadLook()
    {
        if (headLookAmount <= 0f || headLookMaxBlend <= 0f)
        {
            glanceAngle = 0f;
            return;
        }

        switch (glanceStage)
        {
            case 0: // holding the current angle — wait, then glance somewhere
                if (Time.time >= nextGlanceAt) StartGlance(PickNextGlanceTarget());
                else
                {
                    // hold the current angle EXACTLY at glanceTo (no
                    // drift). The saccade end already snapped
                    // glanceAngle to glanceTo, so during hold it
                    // should be the same. We only re-snap here as a
                    // safety net for floating-point rounding.
                    if (!Mathf.Approximately(glanceAngle, glanceTo))
                        glanceAngle = glanceTo;
                }
                break;

            case 1: // easing towards the target angle
            {
                glanceT += Time.deltaTime;
                float u = Mathf.Clamp01(glanceT / glanceDur);
                // smootherstep (6u^5 - 15u^4 + 10u^3): zero velocity and
                // acceleration at both ends
                float eased = u * u * u * (u * (6f * u - 15f) + 10f);
                glanceAngle = Mathf.LerpUnclamped(glanceFrom, glanceTo, eased);
                if (glanceT >= glanceDur)
                {
                    // snap to the exact target so we never hold a
                    // value that is not glanceTo (drift prevention).
                    glanceAngle = glanceTo;
                    glanceStage = 0;
                    glanceT = 0f;
                    // side glances are held shorter than resting at centre
                    nextGlanceAt = Time.time + (Mathf.Approximately(glanceTo, 0f)
                        ? Random.Range(1.6f, 3.5f)
                        : Random.Range(0.8f, 1.8f));
                }
                break;
            }
        }
    }

    /// <summary>Picks the next look angle: side glances (mostly alternating),
    /// returns to centre, occasional cross-over or tiny micro-adjust.
    /// Targets are clamped to a small range so the head never drifts so
    /// far that the eyes look completely off-axis — the gaze should
    /// still feel like "looking around", not "staring at a wall".
    /// Crucially, MOST glances end back at centre (0) — that is what
    /// keeps the face from drifting to one side over time.</summary>
    float PickNextGlanceTarget()
    {
        bool atCentre = Mathf.Approximately(glanceTo, 0f);
        // 0.18 is the smallest glance a human would notice (~4°). The
        // upper bound is headLookMaxBlend (0.5 by default, ~11°), but
        // we cap at 0.32 to keep glances subtle.
        float maxAngle = Mathf.Min(headLookMaxBlend, 0.32f);
        float r = Random.value;

        if (atCentre)
        {
            if (r < 0.55f) // a proper glance to one side
            {
                int side = Random.value < 0.78f ? -lastLookSide : lastLookSide;
                lastLookSide = side;
                return side * Random.Range(0.18f, maxAngle);
            }
            // small curious micro-adjust around centre
            return (Random.value < 0.5f ? -1f : 1f) * Random.Range(0.10f, 0.18f);
        }

        // When we are holding a side angle, MOST of the time we go
        // back to centre (0.85). That makes the face return to forward
        // quickly, which is the whole point of the "idle gaze" feel —
        // otherwise the head would wander off-axis and stay there.
        if (r < 0.85f) return 0f;
        if (r < 0.95f)              // sweep across to the other side
        {
            lastLookSide = -lastLookSide;
            return lastLookSide * Random.Range(0.18f, maxAngle);
        }
        // resettle at a slightly different angle on the same side
        return glanceTo >= 0f ? Random.Range(0.18f, maxAngle)
                              : -Random.Range(0.18f, maxAngle);
    }

    void StartGlance(float target)
    {
        glanceFrom = glanceAngle;
        glanceTo = target;
        // bigger turns take proportionally longer → same peak speed
        glanceDur = 0.55f + 0.28f * Mathf.Abs(glanceTo - glanceFrom);
        glanceT = 0f;
        glanceStage = 1;
    }

    void UpdateBlink()
    {
        if (!blink) { blinkAmount = 0f; return; }

        switch (blinkStage)
        {
            case 0: // waiting for the next blink
                blinkAmount = 0f;
                if (Time.time >= nextBlinkAt)
                {
                    blinkStage = 1;
                    blinkTimer = 0f;
                }
                break;
            case 1: // lids closing (quick, 90 ms)
                blinkTimer += Time.deltaTime;
                blinkAmount = Mathf.Clamp01(blinkTimer / 0.09f);
                if (blinkAmount >= 1f) { blinkStage = 2; blinkTimer = 0f; }
                break;
            case 2: // lids opening (slightly slower, 130 ms)
                blinkTimer += Time.deltaTime;
                blinkAmount = 1f - Mathf.Clamp01(blinkTimer / 0.13f);
                if (blinkAmount <= 0f)
                {
                    blinkStage = 0;
                    if (queuedDoubleBlink)
                    {
                        queuedDoubleBlink = false;
                        nextBlinkAt = Time.time + 0.18f;   // quick second blink
                    }
                    else
                    {
                        queuedDoubleBlink = Random.value < doubleBlinkChance;
                        // 2.5..4.5 s by default, with small per-instance
                        // jitter so the character feels alive, not
                        // metronome-precise.
                        float min = Mathf.Min(blinkMinDelay, blinkMaxDelay);
                        float max = Mathf.Max(blinkMinDelay, blinkMaxDelay);
                        nextBlinkAt = Time.time + Random.Range(min, max);
                    }
                }
                break;
        }
    }

    void LateUpdate()
    {
        Camera cam = Camera.main;
        if (cam == null || sr == null || DirCount < 2) return;
        float dt = Mathf.Max(Time.deltaTime, 1e-5f);

        // ---- 1) compute `rel`: the camera's position relative to the
        //         character, measured in degrees CLOCKWISE from the
        //         direction the character is FACING.
        //
        //   We ALWAYS use the character's movement direction
        //   (the Facing vector) to compute this — even when the
        //   character quad is forced to face the camera. The quad
        //   rotation is a separate concern (see step 4); the SPRITE
        //   INDEX must change when the user presses W/A/S/D, so
        //   rel must depend on the movement direction.
        //
        //   rel = 0   -> camera is directly behind the character
        //                (both face the same way — char is walking
        //                away from the camera)
        //   rel = 90  -> camera is to the character's left
        //   rel = 180 -> camera is in front of the character
        //                (char is walking toward the camera)
        //   rel = 270 -> camera is to the character's right
        // ----
        float camYaw = cam.transform.eulerAngles.y;
        float facingAngle = Mathf.Atan2(Facing.x, Facing.z) * Mathf.Rad2Deg;
        float rel = facingAngle - camYaw;
        rel = ((rel % 360f) + 360f) % 360f;
        if (mirrorLeftRight) rel = (360f - rel) % 360f;

        // ---- 3) orbit lean (purely visual, OFF by default) ----
        // Lean would tilt the sprite around the Y axis, but since we are
        // a normal 2D quad with a non-billboard shader, lean must be 0
        // or it shears the sprite. We still compute it for inspector
        // feedback, but the rotation in step 4 is not contaminated by it.
        float relVel = Mathf.DeltaAngle(prevRelAngle, rel) / dt;
        prevRelAngle = rel;
        float targetLean = Mathf.Clamp(relVel / 90f, -1f, 1f) * orbitLeanDegrees;
        if (invertLean) targetLean = -targetLean;
        lean = Mathf.Lerp(lean, targetLean, 1f - Mathf.Exp(-leanSmoothing * dt));

        // ---- 4) set the character rotation ONCE, from a single source ----
        // The character quad is a normal 2D SpriteRenderer — the shader
        // does NOT bill board the quad to the camera per-vertex. So we
        // must set the rotation ourselves. Two options:
        //
        //   (a) characterFacesMovement = true  (default): the quad rotates
        //       to face the character direction. The sprite INDEX is then
        //       chosen to show the view from the camera's angle — this is
        //       the "turntable while walking" feel, but it CAN look weird
        //       when the camera and character diverge (the quad is no
        //       longer camera-facing and you see a thin edge).
        //
        //   (b) characterFacesMovement = false: the quad ALWAYS faces the
        //       camera, like a true billboard. The sprite INDEX is chosen
        //       the same way (from `rel`). This is the safe default that
        //       can NEVER look sheared, because the quad is flat against
        //       the camera no matter what the user does with WASD.
        //
        // Option (b) is what we set as the default below to fix the
        // "edge-on paper thin" bug the user reported.
        if (characterFacesMovement)
        {
            transform.rotation = Quaternion.Euler(0f, facingAngle, 0f);
        }
        else
        {
            transform.rotation = Quaternion.Euler(0f, camYaw, 0f);
        }

        // ---- 5) continuous direction index from the SAME rel ----
        // The 16 sprites are a turntable of the CHARACTER viewed from
        // the CAMERA's position. The naming is "00_front" = the sprite
        // that should be drawn when the CAMERA is in front of the
        // character (i.e. the camera is on the opposite side of the
        // character from his nose). We compute the sprite index as:
        //   sprite = (rel / bin + 0.5 * DirCount) mod DirCount
        // because:
        //   rel = 0   -> camera behind character (same facing)  -> back  (sprite 8)
        //   rel = 90  -> camera to character's left              -> left  (sprite 12)
        //   rel = 180 -> camera in front of character (opposite) -> front (sprite 0)
        //   rel = 270 -> camera to character's right             -> right (sprite 4)
        float bin = 360f / DirCount;
        float offset = DirCount * 0.5f;
        float targetIdx = (rel / bin + offset);
        if (turnSmoothTime <= 0f)
        {
            // Hysteresis: only switch to a NEW sprite once we are at
            // least HYST degrees past the seam toward that sprite.
            // Without this, tiny camera wobble around the seam (e.g.
            // when the user is walking forward WHILE gently orbiting
            // the camera) makes the sprite flicker between two
            // neighbours ("kabhi tedha kabhi seedha").
            const float HYST = 2.0f;   // degrees of deadband
            float currentCentre = ((contDir - offset) / DirCount) * 360f;
            // wrap the "current centre" so it is in [-180, 180]
            currentCentre = Mathf.DeltaAngle(currentCentre, 0f);
            float dToCur = Mathf.Abs(Mathf.DeltaAngle(currentCentre, rel));
            int snapped;
            if (dToCur < bin * 0.5f - HYST)
            {
                // still inside the current sprite's territory, keep it
                snapped = (int)Mathf.Round(contDir);
            }
            else
            {
                // we are past the boundary — take the round
                snapped = (int)Mathf.Round(targetIdx);
            }
            contDir = Mathf.Repeat(snapped, DirCount);
            contDirVel = 0f;
        }
        else
        {
            // wrap-aware smoothing (handles the 16 -> 0 seam)
            float curDeg = (contDir - offset) / DirCount * 360f;
            float diffIdx = Mathf.DeltaAngle(curDeg, rel) / 360f * DirCount;
            contDir = Mathf.SmoothDamp(contDir, contDir + diffIdx, ref contDirVel, turnSmoothTime);
            contDir = Mathf.Repeat(contDir, DirCount);
        }
        // ---- 5a) back/front strict snap: when the camera is behind
        //         the character (|rel - 0| < 8°), always show the
        //         pure-back sprite; when the camera is in front
        //         (|rel - 180| < 8°), always show the pure-front
        //         sprite. This makes the back / front keys feel
        //         rock-solid, never ambiguous. ----
        if (turnSmoothTime <= 0f)
        {
            float dToBack = Mathf.Abs(Mathf.DeltaAngle(rel, 0f));
            if (dToBack < 8f) contDir = DirCount * 0.5f;     // sprite 8
            float dToFront = Mathf.Abs(Mathf.DeltaAngle(rel, 180f));
            if (dToFront < 8f) contDir = 0f;                 // sprite 0
        }

        int a = Mathf.Min((int)contDir, DirCount - 1);
        int b = (a + 1) % DirCount;
        float frac = contDir - a;

        if (a != dirA) BindDirection(a, false);
        mat.SetFloat(ID_Blend, frac);
        mat.SetFloat(ID_BlendSharp, blendSharpness);
        mat.SetFloat(ID_BlendUnion, solidSilhouetteWhileBlending ? 1f : 0f);
        mat.SetFloat(ID_MoveBlend, moveBlend);
        mat.SetFloat(ID_MovePhase, movePhase);
        mat.SetFloat(ID_Blink, blinkAmount);
        // pushed every frame so an old material that was authored
        // before the toggle existed cannot leave the shader with
        // cutTransparentGreenEdges = 0 and reintroduce the green fringe
        mat.SetFloat(ID_AlphaClip, cutTransparentGreenEdges ? 1f : 0f);
        mat.SetFloat(ID_AlphaClipThr, transparentEdgeCutoff);

        // head glance: cross-fade the head toward the neighbouring view
        // (a REAL head turn — the artist's own pixels). Faded out while the
        // direction glides or the character walks: the head returns to
        // centre then, like a real person, and never fights the orbit blend.
        float turnFade = 1f - Mathf.SmoothStep(0.15f, 0.9f, Mathf.Abs(contDirVel));
        float glance = glanceAngle * headLookAmount * turnFade * (1f - moveBlend);
        mat.SetFloat(ID_HeadGlance, Mathf.Clamp(glance, -1f, 1f));

        // ---- 6) wind: project the world wind onto the camera's right axis so
        //          orbiting changes the apparent sway direction naturally ----
        Vector3 wind = new Vector3(windDirection.x, 0f, windDirection.y);
        float screenX = wind.sqrMagnitude > 0.0001f
            ? Vector3.Dot(wind.normalized, cam.transform.right)
            : 0f;
        mat.SetFloat(ID_WindDirX, screenX);
        mat.SetFloat(ID_HairAmp, hairSwayPixels * windStrength);
        mat.SetFloat(ID_ClothAmp, clothFlutterPixels * windStrength);

        // ---- 7) environment: pull from the global TimeOfDay/Weather
        //          singleton if asked, then push everything into the
        //          shader. Each property is read every frame so a
        //          changing global state shows up immediately and
        //          older materials cannot leave the values stale. ----
        if (followGlobalEnvironment && TimeOfDayWeather.Instance != null)
        {
            TimeOfDayWeather env = TimeOfDayWeather.Instance;
            daylight    = env.Daylight;
            ambientTint = env.AmbientTint;
            wetness     = env.Wetness;
            wetShine    = env.WetShine;
            darkness    = env.Darkness;
        }
        mat.SetFloat(ID_Daylight, daylight);
        mat.SetColor(ID_AmbientTint, ambientTint);
        mat.SetFloat(ID_Wetness, wetness);
        mat.SetFloat(ID_WetShine, wetShine);
        mat.SetFloat(ID_Darkness, darkness);
    }

    /// <summary>Bind sprite A to the renderer and sprite B + masks to the shader.</summary>
    void BindDirection(int a, bool initial)
    {
        dirA = a;
        int b = (a + 1) % DirCount;
        sr.sprite = directionSprites[a];
        if (mat == null) return;

        mat.SetTexture(ID_TexB, directionSprites[b] != null ? directionSprites[b].texture : null);
        int h = (a - 1 + DirCount) % DirCount;
        mat.SetTexture(ID_TexHead, directionSprites[h] != null ? directionSprites[h].texture : null);

        Texture2D mA = GetMask(a);
        Texture2D mB = GetMask(b);
        mat.SetTexture(ID_MaskA, mA != null ? mA : Texture2D.blackTexture);
        mat.SetTexture(ID_MaskB, mB != null ? mB : Texture2D.blackTexture);

        if (initial)
        {
            // body centre-x in UV space (used by the shader for chest expansion).
            // Sprite mesh space puts the pivot at (0,0); with a centre pivot the
            // content centre in UVs is 0.5 + bounds.centre.x / rect.width.
            Sprite s = directionSprites[a];
            if (s != null)
            {
                float uvCx = 0.5f + s.bounds.center.x / s.textureRect.width;
                mat.SetFloat(ID_BodyCentreX, Mathf.Clamp01(uvCx));
            }
        }
    }

    Texture2D GetMask(int i)
    {
        if (masks == null || masks.Length == 0) return null;
        return i < masks.Length ? masks[i] : null;
    }

    // ------------------------------------------------------------------ input
    void TrySetMoveTarget()
    {
        Camera cam = Camera.main;
        if (cam == null) return;
        Ray ray = cam.ScreenPointToRay(MouseScreenPosition());
        Plane ground = new Plane(Vector3.up, Vector3.zero);
        if (ground.Raycast(ray, out float dist))
            moveTarget = ray.GetPoint(dist);
    }

    static bool MouseLeftClicked()
    {
#if ENABLE_INPUT_SYSTEM
        Mouse m = Mouse.current;
        return m != null && m.leftButton.wasPressedThisFrame;
#else
        return Input.GetMouseButtonDown(0);
#endif
    }

    static Vector3 MouseScreenPosition()
    {
#if ENABLE_INPUT_SYSTEM
        Mouse m = Mouse.current;
        return m != null ? (Vector3)m.position.ReadValue() : Vector3.zero;
#else
        return Input.mousePosition;
#endif
    }

    // ------------------------------------------------------------------ API
    /// <summary>Change the breeze at runtime (weather system hook).</summary>
    public void SetWind(Vector2 worldDirection, float strength)
    {
        windDirection = worldDirection.sqrMagnitude > 0.001f ? worldDirection.normalized : Vector2.right;
        windStrength = strength;
    }
}
