using System.Collections.Generic;
using UnityEngine;
#if ENABLE_INPUT_SYSTEM
using UnityEngine.InputSystem;
#endif

/// <summary>
/// GTA V-style third-person controller for the billboarded caveman — SMOOTH edition.
///
/// What makes it feel 3-dimensional instead of "flipping paper cut-outs":
///  1. CONTINUOUS DIRECTION CROSS-FADE — the exact camera↔character angle maps to a
///     floating direction index (e.g. 4.37). The shader cross-fades between the two
///     neighbouring direction sprites, so orbiting the camera morphs smoothly
///     through every in-between angle instead of snapping between 8/16 sprites.
///  2. TURN GLIDE — the floating index is time-smoothed, so when the player changes
///     direction the character visibly glides through the in-between poses.
///  3. ORBIT LEAN — while the camera orbits or the character turns, the quad leans
///     a few degrees into the motion, faking rotational inertia/mass.
///  4. LIVING IDLE — the shader (Game/BillboardBlendWind) animates hair sway,
///     loincloth flutter and breathing on the GPU, driven by generated sway masks.
///     This script adds eased HEAD GLANCES — the head region cross-fades
///     toward the neighbouring direction view (a real head turn using the
///     artist's own pixels) — plus natural eye blinks; all perfectly smooth.
///
/// Setup: add this INSTEAD of PlayerController3D + IdleAnimator, assign the 16
/// direction sprites (and optionally the 16 sway masks), and give the
/// SpriteRenderer the "Game/BillboardBlendWind" material. The material is
/// instanced automatically per character, so every caveman can have its own
/// wind phase / tint.
/// </summary>
[DefaultExecutionOrder(10)] // after ThirdPersonCamera so the billboard uses the final camera pose
public class BillboardCharacter : MonoBehaviour
{
    [Header("Sprites — turntable order")]
    [Tooltip("Front, then rotating around the character (00_front, 01_front_right_slight, ... 15_front_left_slight).\n" +
             "All sprites MUST be the same pixel size and NOT packed into a sprite atlas.")]
    public Sprite[] directionSprites;

    [Header("Sway masks (same order as sprites)")]
    [Tooltip("R = hair, G = cloth/loincloth, B = torso/breathing. Generated by tools/generate_sway_masks.py.\n" +
             "Import them as plain textures (default import settings) and leave this empty to auto-load\n" +
             "them from Resources/CharacterMasks/<sprite name>_mask. Without masks a procedural fallback is used.")]
    public Texture2D[] directionMasks;

    [Tooltip("If directionMasks is empty, try Resources/CharacterMasks/<sprite name>_mask automatically.")]
    public bool autoLoadMasksFromResources = true;

    [Header("Movement")]
    public float moveSpeed = 5f;
    public float stopDistance = 0.15f;
    public bool clickToMove = true;

    [Header("Direction blending")]
    [Tooltip("Seconds the direction takes to glide when the camera orbits / he turns.\n0.10–0.20 = smooth and alive.")]
    public float turnSmoothTime = 0.08f;

    [Tooltip("How sharply the two neighbouring direction sprites cross-fade.\n" +
             "1 = an almost instant swap (zero ghosting/double-image), 0 = a long soft fade.\n" +
             "0.75+ removes the 'a second faint sprite is showing through' look.")]
    [Range(0f, 1f)] public float blendSharpness = 0.8f;

    [Tooltip("Keep the silhouette fully opaque while two views cross-fade (prevents the see-through/blurry frame).")]
    public bool solidSilhouetteWhileBlending = true;

    [Tooltip("Tick if he faces the wrong way when strafing left/right.")]
    public bool mirrorLeftRight = false;

    [Header("Orbit lean (fake rotational inertia)")]
    [Tooltip("Degrees the sprite leans while the camera orbits or he turns. 0 = off.")]
    public float orbitLeanDegrees = 3.5f;
    public float leanSmoothing = 6f;
    public bool invertLean = false;

    [Header("Wind")]
    [Tooltip("World XZ direction the breeze blows towards.")]
    public Vector2 windDirection = new Vector2(1f, 0.25f);

    [Tooltip("Global wind strength (scales hair + cloth sway).")]
    public float windStrength = 1f;

    public float windSpeed = 1.6f;

    [Tooltip("Hair sway amplitude in pixels (relative to the sprite width).")]
    public float hairSwayPixels = 3.0f;

    [Tooltip("Loincloth flutter amplitude in pixels. 0 = bottom cloth stays still (default).\nRaise to ~3.6 if you want the hem to flutter in the breeze again.")]
    public float clothFlutterPixels = 0f;

    [Header("Breathing / idle life")]
    [Tooltip("Breaths per second. 0.22 ≈ 13 breaths/min.")]
    public float breathsPerSecond = 0.235f;

    [Range(0f, 2f)] public float breathAmount = 1.05f;
    [Range(0f, 3f)] public float idleBodyBob = 1f;

    [Header("Head + eyes")]
    [Tooltip("How strongly the head glances left/right while idle. 0 = still head, 1 = default.")]
    [Range(0f, 2f)] public float headLookAmount = 1f;

    [Tooltip("How far the head turns when glancing, as a fraction of one direction step (0.85 ≈ 19°, a natural glance).")]
    [Range(0.2f, 1f)] public float headLookMaxBlend = 0.85f;

    [Tooltip("Blink naturally while idle.")]
    public bool blink = true;
    public float blinkMinDelay = 2.5f;
    public float blinkMaxDelay = 6.5f;
    [Tooltip("Chance to blink twice in a row.")]
    [Range(0f, 1f)] public float doubleBlinkChance = 0.18f;

    [Header("Hands")]
    [Tooltip("Slow fist clench (finger curl) amount. 0 = off.")]
    [Range(0f, 2f)] public float fingerCurlAmount = 1f;

    [Header("Walking")]
    [Range(0f, 3f)] public float walkBobAmount = 1f;
    [Tooltip("Stride cycles per second at full speed.")]
    public float strideRate = 1.4f;

    [Header("Contact shadow")]
    [Tooltip("Soft dark blob under his feet (drawn by the shader). 0 = off.")]
    [Range(0f, 1f)] public float contactShadowStrength = 0.38f;

    [Header("Green-screen cleanup")]
    [Tooltip("Cut leftover keyed-green fringe. Driven every frame so an old material cannot leave the shader toggle off.")]
    public bool cutTransparentGreenEdges = true;
    [Range(0f, 0.5f)] public float transparentEdgeCutoff = 0.10f;

    [Header("Misc")]
    [Tooltip("Randomize wind/breath phase so multiple characters don't animate in sync.")]
    public bool randomPhasePerInstance = true;

    // ---------------- public state (handy for other scripts) ----------------
    /// <summary>World-space facing direction.</summary>
    public Vector3 Facing { get; private set; } = Vector3.forward;

    /// <summary>Continuous direction index, e.g. 4.37 = 37% between sprite 4 and 5.</summary>
    public float ContinuousDirection => contDir;

    /// <summary>Nearest discrete direction index (compatibility with old scripts).</summary>
    public int CurrentDirectionIndex => ((int)contDir) % DirCount;

    /// <summary>True while the character is moving.</summary>
    public bool IsMoving { get; private set; }

    // ---------------- internals ----------------
    static readonly int ID_TexB          = Shader.PropertyToID("_TexB");
    static readonly int ID_MaskA         = Shader.PropertyToID("_MaskA");
    static readonly int ID_MaskB         = Shader.PropertyToID("_MaskB");
    static readonly int ID_Blend         = Shader.PropertyToID("_Blend");
    static readonly int ID_BlendSharp    = Shader.PropertyToID("_BlendSharp");
    static readonly int ID_BlendUnion    = Shader.PropertyToID("_BlendAlphaUnion");
    static readonly int ID_WindDirX      = Shader.PropertyToID("_WindDirX");
    static readonly int ID_WindSpeed     = Shader.PropertyToID("_WindSpeed");
    static readonly int ID_HairAmp       = Shader.PropertyToID("_HairAmp");
    static readonly int ID_ClothAmp      = Shader.PropertyToID("_ClothAmp");
    static readonly int ID_HeadGlance   = Shader.PropertyToID("_HeadGlance");
    static readonly int ID_TexHead      = Shader.PropertyToID("_TexHead");
    static readonly int ID_Blink         = Shader.PropertyToID("_Blink");
    static readonly int ID_ClenchAmp     = Shader.PropertyToID("_ClenchAmp");
    static readonly int ID_BreathRate    = Shader.PropertyToID("_BreathRate");
    static readonly int ID_BreathAmp     = Shader.PropertyToID("_BreathAmp");
    static readonly int ID_BobAmp        = Shader.PropertyToID("_BobAmp");
    static readonly int ID_MoveBlend     = Shader.PropertyToID("_MoveBlend");
    static readonly int ID_MovePhase     = Shader.PropertyToID("_MovePhase");
    static readonly int ID_StrideAmp     = Shader.PropertyToID("_StrideAmp");
    static readonly int ID_ShadowStr     = Shader.PropertyToID("_ShadowStrength");
    static readonly int ID_TexSize       = Shader.PropertyToID("_TexSize");
    static readonly int ID_BodyCentreX   = Shader.PropertyToID("_BodyCentreX");
    static readonly int ID_Phase         = Shader.PropertyToID("_Phase");
    static readonly int ID_FallbackMask  = Shader.PropertyToID("_FallbackMask");
    static readonly int ID_AlphaClip     = Shader.PropertyToID("_AlphaClip");
    static readonly int ID_AlphaClipThr  = Shader.PropertyToID("_AlphaClipThreshold");

    // Textures already scanned for green key spill this session (avoids
    // running GetPixels32 again on every Awake).
    static readonly HashSet<int> greenCheckedTextures = new HashSet<int>();

    SpriteRenderer sr;
    Material mat;
    Vector3? moveTarget;
    Vector3 moveDir;
    float contDir;          // smoothed continuous direction index
    float contDirVel;       // SmoothDamp velocity
    int dirA = -1;          // which sprite is currently bound to _MainTex
    float lean;             // current orbit-lean (degrees)
    float prevRelAngle;     // for angular velocity
    float moveBlend;        // 0 idle .. 1 full speed (smoothed)
    float moveBlendVel;
    float movePhase;        // stride cycle
    Texture2D[] masks;      // resolved masks (may be null entries)
    bool usingFallbackMask;

    // blink state machine
    float nextBlinkAt;
    int blinkStage;         // 0 idle, 1 closing, 2 opening
    float blinkTimer;
    float blinkAmount;      // 0 open .. 1 closed
    bool queuedDoubleBlink;

    // head-glance state machine (looking left / right a little)
    float glanceAngle;      // current head turn, degrees (+ = one side, - = other)
    float glanceFrom, glanceTo, glanceT, glanceDur;
    float nextGlanceAt;
    int glanceStage;        // 0 holding, 1 turning
    int lastLookSide;       // +/- 1, so glances mostly alternate

    int DirCount => directionSprites == null ? 0 : directionSprites.Length;

    // ------------------------------------------------------------------ setup
    void Awake()
    {
        sr = GetComponent<SpriteRenderer>();
        if (sr == null)
        {
            Debug.LogError("BillboardCharacter: no SpriteRenderer on this object.", this);
            enabled = false;
            return;
        }
        if (DirCount < 2)
        {
            Debug.LogError("BillboardCharacter: assign at least 2 direction sprites.", this);
            enabled = false;
            return;
        }
        for (int i = 0; i < directionSprites.Length; i++)
        {
            if (directionSprites[i] == null)
                Debug.LogError($"BillboardCharacter: directionSprites[{i}] is null.", this);
            else if (directionSprites[i].packed)
                Debug.LogError("BillboardCharacter: sprites are packed into a SpriteAtlas — " +
                               "the blend shader needs standalone textures. Remove them from the atlas.", this);
        }

        // instance the material so each character can have its own wind phase
        mat = sr.material;
        if (!mat.shader.name.Contains("BillboardBlendWind"))
            Debug.LogWarning("BillboardCharacter: the SpriteRenderer's material does not use the " +
                             "Game/BillboardBlendWind shader — smooth blending and wind will not show. " +
                             "Create a material from BillboardBlendWind.shader and assign it.", this);

        ResolveMasks();
        ForceClampWrap();
        WarnIfSpritesStillHaveGreenKey();

        // Preserve the direction the object was authored with until the first
        // movement input.  This matters when the camera uses that initial
        // facing to place itself behind the player; leaving Facing at the
        // hard-coded +Z default makes a rotated player begin in a side view.
        Vector3 initialFacing = transform.forward;
        initialFacing.y = 0f;
        if (initialFacing.sqrMagnitude > 0.001f)
            Facing = initialFacing.normalized;

        contDir = DirCount * 0.5f;                 // start facing away from the camera (back view)
        BindDirection(DirCount / 2, true);
        prevRelAngle = 180f;

        mat.SetFloat(ID_Phase, randomPhasePerInstance ? Random.value * 100f : 0f);
        mat.SetFloat(ID_WindSpeed, windSpeed);
        mat.SetFloat(ID_BreathRate, breathsPerSecond);
        mat.SetFloat(ID_BreathAmp, breathAmount);
        mat.SetFloat(ID_BobAmp, idleBodyBob);
        mat.SetFloat(ID_ClenchAmp, fingerCurlAmount);
        glanceStage = 0;
        glanceAngle = 0f;
        nextGlanceAt = Time.time + Random.Range(0.6f, 1.8f);
        lastLookSide = Random.value < 0.5f ? -1 : 1;
        nextBlinkAt = Time.time + Random.Range(blinkMinDelay, blinkMaxDelay);
        mat.SetFloat(ID_StrideAmp, walkBobAmount);
        mat.SetFloat(ID_ShadowStr, contactShadowStrength);
        mat.SetFloat(ID_FallbackMask, usingFallbackMask ? 1f : 0f);

        var t0 = directionSprites[0];
        if (t0 != null && t0.texture != null)
            mat.SetVector(ID_TexSize, new Vector4(t0.texture.width, t0.texture.height, 0, 0));
    }

    void ResolveMasks()
    {
        masks = directionMasks;
        if ((masks == null || masks.Length == 0) && autoLoadMasksFromResources)
        {
            var loaded = new List<Texture2D>(DirCount);
            for (int i = 0; i < DirCount; i++)
            {
                Sprite s = directionSprites[i];
                Texture2D m = s != null
                    ? Resources.Load<Texture2D>($"CharacterMasks/{s.name}_mask")
                    : null;
                loaded.Add(m);
            }
            masks = loaded.ToArray();
        }

        int have = 0;
        if (masks != null)
            for (int i = 0; i < masks.Length; i++)
                if (masks[i] != null) have++;

        usingFallbackMask = have == 0;
        if (have > 0 && have < DirCount)
            Debug.LogWarning($"BillboardCharacter: only {have}/{DirCount} sway masks assigned — " +
                             "missing directions will not sway. (Masks: tools/generate_sway_masks.py)", this);
    }

    void ForceClampWrap()
    {
        // Repeat wrap on a green-keyed sprite turns UV displacement (hair/breath)
        // into a lime streak from the opposite edge of the texture.
        for (int i = 0; i < DirCount; i++)
        {
            Sprite s = directionSprites[i];
            if (s != null && s.texture != null)
                s.texture.wrapMode = TextureWrapMode.Clamp;
        }
        if (masks == null) return;
        for (int i = 0; i < masks.Length; i++)
            if (masks[i] != null)
                masks[i].wrapMode = TextureWrapMode.Clamp;
    }

    /// <summary>
    /// The shipped sprites are re-keyed (they contain ZERO green-dominant
    /// pixels). If the assigned sprites still contain green key pixels, the
    /// project is using outdated PNGs — the old ones have a soft lime fringe
    /// that renders as the green streaks. Say exactly that on the console
    /// instead of rendering silently.
    /// </summary>
    void WarnIfSpritesStillHaveGreenKey()
    {
        if (directionSprites == null) return;
        bool anyBad = false;
        int scanned = 0;
        for (int i = 0; i < directionSprites.Length && scanned < 4; i++)
        {
            Sprite s = directionSprites[i];
            if (s == null || s.texture == null) continue;
            if (!greenCheckedTextures.Add(s.texture.GetInstanceID())) continue;
            scanned++;

            try
            {
                Color32[] px = s.texture.GetPixels32();
                int green = 0;
                for (int j = 0; j < px.Length; j++)
                {
                    Color32 p = px[j];
                    if (p.a > 2 && p.g - Mathf.Max(p.r, p.b) > 4) green++;
                }

                if (green > 0)
                {
                    anyBad = true;
                    Debug.LogError(
                        $"{name}: sprite '{s.name}' still contains {green} green screen-key pixels " +
                        "— you are using the OLD sprite PNGs (they were re-keyed; current PNGs have zero green). " +
                        "Copy the current sprites_16 / sprites_16_idle PNGs and both shaders over the Assets copies, " +
                        "then Assets > Reimport All and recreate the material from the current shader.",
                        this);
                }
            }
            catch (System.Exception e)
            {
                Debug.LogWarning($"{name}: could not scan '{s.name}' for green key pixels ({e.Message}).", this);
            }
        }

        if (anyBad)
            Debug.LogError(
                $"{name}: green streaks are caused by outdated sprite textures — see Unity_Smooth_Billboard_Setup.md > Troubleshooting.",
                this);
    }

    // ------------------------------------------------------------------ update
    void Update()
    {
        moveDir = Vector3.zero;

        float h = 0f, v = 0f;
#if ENABLE_INPUT_SYSTEM
        Keyboard kb = Keyboard.current;
        if (kb != null)
        {
            if (kb.wKey.isPressed || kb.upArrowKey.isPressed)    v += 1f;
            if (kb.sKey.isPressed || kb.downArrowKey.isPressed)  v -= 1f;
            if (kb.dKey.isPressed || kb.rightArrowKey.isPressed) h += 1f;
            if (kb.aKey.isPressed || kb.leftArrowKey.isPressed)  h -= 1f;
        }
        Gamepad pad = Gamepad.current;
        if (pad != null)
        {
            Vector2 st = pad.leftStick.ReadValue();
            h += Mathf.Abs(st.x) > 0.15f ? st.x : 0f;
            v += Mathf.Abs(st.y) > 0.15f ? st.y : 0f;
        }
#else
        h = Input.GetAxisRaw("Horizontal");
        v = Input.GetAxisRaw("Vertical");
#endif

        if (Mathf.Abs(h) > 0.01f || Mathf.Abs(v) > 0.01f)
        {
            moveTarget = null;
            Camera cam = Camera.main;
            Vector3 f = cam ? cam.transform.forward : Vector3.forward; f.y = 0f; f.Normalize();
            Vector3 r = cam ? cam.transform.right   : Vector3.right;    r.y = 0f; r.Normalize();
            moveDir = (f * v + r * h).normalized;
        }
        else if (clickToMove && MouseLeftClicked())
        {
            TrySetMoveTarget();
        }

        if (moveTarget.HasValue)
        {
            Vector3 to = moveTarget.Value - transform.position;
            to.y = 0f;
            if (to.magnitude <= stopDistance) moveTarget = null;
            else moveDir = to.normalized;
        }

        bool moving = moveDir.sqrMagnitude > 0.001f;
        IsMoving = moving;
        if (moving)
        {
            transform.position += moveDir * moveSpeed * Time.deltaTime;
            Facing = moveDir.normalized;
        }

        UpdateBlink();
        UpdateHeadLook();

        // smoothed move blend + stride phase for the walk bob
        float targetBlend = moving ? 1f : 0f;
        moveBlend = Mathf.SmoothDamp(moveBlend, targetBlend, ref moveBlendVel, 0.18f);
        if (moving) movePhase += Time.deltaTime * strideRate * (moveSpeed > 0f ? 1f : 0f);
        movePhase = Mathf.Repeat(movePhase, 1f);
    }

    /// <summary>
    /// Natural idle head GLANCES: the head eases to a small look angle, holds
    /// it briefly, and eases back — like a person idly looking left and right.
    /// The angle cross-fades the head region toward the NEIGHBOURING direction
    /// view, so the head really turns (the artist's own pixels change — see
    /// the shader's _HeadGlance/_TexHead).
    /// Every turn uses smootherstep easing (zero velocity AND acceleration at
    /// both ends), so the motion is perfectly smooth by construction: no
    /// wobble, no drift, no per-frame randomness while turning.
    /// </summary>
    void UpdateHeadLook()
    {
        if (headLookAmount <= 0f || headLookMaxBlend <= 0f)
        {
            glanceAngle = 0f;
            return;
        }

        switch (glanceStage)
        {
            case 0: // holding the current angle — wait, then glance somewhere
                if (Time.time >= nextGlanceAt) StartGlance(PickNextGlanceTarget());
                break;

            case 1: // easing towards the target angle
            {
                glanceT += Time.deltaTime;
                float u = Mathf.Clamp01(glanceT / glanceDur);
                // smootherstep (6u^5 - 15u^4 + 10u^3): eases in AND out
                u = u * u * u * (u * (6f * u - 15f) + 10f);
                glanceAngle = Mathf.Lerp(glanceFrom, glanceTo, u);
                if (glanceT >= glanceDur)
                {
                    glanceAngle = glanceTo;
                    glanceStage = 0;
                    // side glances are held shorter than resting at centre
                    nextGlanceAt = Time.time + (Mathf.Approximately(glanceTo, 0f)
                        ? Random.Range(1.6f, 4.5f)
                        : Random.Range(0.9f, 2.4f));
                }
                break;
            }
        }

        // the shader value is pushed in LateUpdate, where the turn/walk fades
        // are known (the glance must not fight the direction cross-fade)
    }

    /// <summary>Picks the next look angle: side glances (mostly alternating),
    /// returns to centre, occasional cross-over or tiny micro-adjust.</summary>
    float PickNextGlanceTarget()
    {
        bool atCentre = Mathf.Approximately(glanceTo, 0f);
        float r = Random.value;

        if (atCentre)
        {
            if (r < 0.72f) // a proper glance to one side
            {
                int side = Random.value < 0.78f ? -lastLookSide : lastLookSide;
                lastLookSide = side;
                return side * Random.Range(0.45f, headLookMaxBlend);
            }
            // small curious micro-adjust around centre
            return (Random.value < 0.5f ? -1f : 1f) * Random.Range(0.12f, 0.25f);
        }

        if (r < 0.70f) return 0f;   // back to centre
        if (r < 0.85f)              // sweep across to the other side
        {
            lastLookSide = -lastLookSide;
            return lastLookSide * Random.Range(0.60f, headLookMaxBlend);
        }
        // resettle at a slightly different angle on the same side
        return glanceTo >= 0f ? Random.Range(0.40f, headLookMaxBlend)
                              : -Random.Range(0.40f, headLookMaxBlend);
    }

    void StartGlance(float target)
    {
        glanceFrom = glanceAngle;
        glanceTo = target;
        // bigger turns take proportionally longer → same peak speed
        glanceDur = 0.55f + 0.28f * Mathf.Abs(glanceTo - glanceFrom);
        glanceT = 0f;
        glanceStage = 1;
    }

    void UpdateBlink()
    {
        if (!blink) { blinkAmount = 0f; return; }

        switch (blinkStage)
        {
            case 0: // waiting for the next blink
                blinkAmount = 0f;
                if (Time.time >= nextBlinkAt)
                {
                    blinkStage = 1;
                    blinkTimer = 0f;
                }
                break;
            case 1: // lids closing (quick)
                blinkTimer += Time.deltaTime;
                blinkAmount = Mathf.Clamp01(blinkTimer / 0.09f);
                if (blinkAmount >= 1f) { blinkStage = 2; blinkTimer = 0f; }
                break;
            case 2: // lids opening (slightly slower)
                blinkTimer += Time.deltaTime;
                blinkAmount = 1f - Mathf.Clamp01(blinkTimer / 0.13f);
                if (blinkAmount <= 0f)
                {
                    blinkStage = 0;
                    if (queuedDoubleBlink)
                    {
                        queuedDoubleBlink = false;
                        nextBlinkAt = Time.time + 0.16f;   // quick second blink
                    }
                    else
                    {
                        queuedDoubleBlink = Random.value < doubleBlinkChance;
                        nextBlinkAt = Time.time + Random.Range(blinkMinDelay, blinkMaxDelay);
                    }
                }
                break;
        }
    }

    void LateUpdate()
    {
        Camera cam = Camera.main;
        if (cam == null || sr == null || DirCount < 2) return;
        float dt = Mathf.Max(Time.deltaTime, 1e-5f);

        // ---- 1) relative yaw between camera and character facing ----
        float camYaw = cam.transform.eulerAngles.y;
        float facingAngle = Mathf.Atan2(Facing.x, Facing.z) * Mathf.Rad2Deg;
        float rel = Mathf.DeltaAngle(camYaw, facingAngle);
        if (rel < 0f) rel += 360f;
        if (mirrorLeftRight) rel = (360f - rel) % 360f;

        // ---- 2) orbit lean: lean into camera orbit / character turns ----
        float relVel = Mathf.DeltaAngle(prevRelAngle, rel) / dt;   // deg/sec
        prevRelAngle = rel;
        float targetLean = Mathf.Clamp(relVel / 90f, -1f, 1f) * orbitLeanDegrees;
        if (invertLean) targetLean = -targetLean;
        lean = Mathf.Lerp(lean, targetLean, 1f - Mathf.Exp(-leanSmoothing * dt));

        // ---- 3) upright billboard (yaw only) + lean ----
        transform.rotation = Quaternion.Euler(0f, camYaw + lean, 0f);

        // ---- 4) continuous direction index, time-smoothed (turn glide) ----
        float bin = 360f / DirCount;
        float targetIdx = (180f - rel) / bin;
        // wrap-aware smoothing (handles the 16 -> 0 seam)
        float curDeg = contDir / DirCount * 360f;
        float tgtDeg = targetIdx / DirCount * 360f;
        float diffIdx = Mathf.DeltaAngle(curDeg, tgtDeg) / 360f * DirCount;
        contDir = Mathf.SmoothDamp(contDir, contDir + diffIdx, ref contDirVel, turnSmoothTime);
        contDir = Mathf.Repeat(contDir, DirCount);

        int a = Mathf.Min((int)contDir, DirCount - 1);
        int b = (a + 1) % DirCount;
        float frac = contDir - a;

        if (a != dirA) BindDirection(a, false);
        mat.SetFloat(ID_Blend, frac);
        mat.SetFloat(ID_BlendSharp, blendSharpness);
        mat.SetFloat(ID_BlendUnion, solidSilhouetteWhileBlending ? 1f : 0f);
        mat.SetFloat(ID_MoveBlend, moveBlend);
        mat.SetFloat(ID_MovePhase, movePhase);
        mat.SetFloat(ID_Blink, blinkAmount);

        // head glance: cross-fade the head toward the neighbouring view
        // (a REAL head turn — the artist's own pixels). Faded out while the
        // direction glides or the character walks: the head returns to
        // centre then, like a real person, and never fights the orbit blend.
        float turnFade = 1f - Mathf.SmoothStep(0.15f, 0.9f, Mathf.Abs(contDirVel));
        float glance = glanceAngle * headLookAmount * turnFade * (1f - moveBlend);
        mat.SetFloat(ID_HeadGlance, Mathf.Clamp(glance, -1f, 1f));

        // ---- 5) wind: project the world wind onto the camera's right axis so
        //          orbiting changes the apparent sway direction naturally ----
        Vector3 wind = new Vector3(windDirection.x, 0f, windDirection.y);
        float screenX = wind.sqrMagnitude > 0.0001f
            ? Vector3.Dot(wind.normalized, cam.transform.right)
            : 0f;
        mat.SetFloat(ID_WindDirX, screenX);
        mat.SetFloat(ID_HairAmp, hairSwayPixels * windStrength);
        mat.SetFloat(ID_ClothAmp, clothFlutterPixels * windStrength);
    }

    /// <summary>Bind sprite A to the renderer and sprite B + masks to the shader.</summary>
    void BindDirection(int a, bool initial)
    {
        dirA = a;
        int b = (a + 1) % DirCount;
        sr.sprite = directionSprites[a];
        if (mat == null) return;

        mat.SetTexture(ID_TexB, directionSprites[b] != null ? directionSprites[b].texture : null);
        int h = (a - 1 + DirCount) % DirCount;
        mat.SetTexture(ID_TexHead, directionSprites[h] != null ? directionSprites[h].texture : null);

        Texture2D mA = GetMask(a);
        Texture2D mB = GetMask(b);
        mat.SetTexture(ID_MaskA, mA != null ? mA : Texture2D.blackTexture);
        mat.SetTexture(ID_MaskB, mB != null ? mB : Texture2D.blackTexture);

        if (initial)
        {
            // body centre-x in UV space (used by the shader for chest expansion).
            // Sprite mesh space puts the pivot at (0,0); with a centre pivot the
            // content centre in UVs is 0.5 + bounds.centre.x / rect.width.
            Sprite s = directionSprites[a];
            if (s != null)
            {
                float uvCx = 0.5f + s.bounds.center.x / s.textureRect.width;
                mat.SetFloat(ID_BodyCentreX, Mathf.Clamp01(uvCx));
            }
        }
    }

    Texture2D GetMask(int i)
    {
        if (masks == null || masks.Length == 0) return null;
        return i < masks.Length ? masks[i] : null;
    }

    // ------------------------------------------------------------------ input
    void TrySetMoveTarget()
    {
        Camera cam = Camera.main;
        if (cam == null) return;
        Ray ray = cam.ScreenPointToRay(MouseScreenPosition());
        Plane ground = new Plane(Vector3.up, Vector3.zero);
        if (ground.Raycast(ray, out float dist))
            moveTarget = ray.GetPoint(dist);
    }

    static bool MouseLeftClicked()
    {
#if ENABLE_INPUT_SYSTEM
        Mouse m = Mouse.current;
        return m != null && m.leftButton.wasPressedThisFrame;
#else
        return Input.GetMouseButtonDown(0);
#endif
    }

    static Vector3 MouseScreenPosition()
    {
#if ENABLE_INPUT_SYSTEM
        Mouse m = Mouse.current;
        return m != null ? (Vector3)m.position.ReadValue() : Vector3.zero;
#else
        return Input.mousePosition;
#endif
    }

    // ------------------------------------------------------------------ API
    /// <summary>Change the breeze at runtime (weather system hook).</summary>
    public void SetWind(Vector2 worldDirection, float strength)
    {
        windDirection = worldDirection.sqrMagnitude > 0.001f ? worldDirection.normalized : Vector2.right;
        windStrength = strength;
    }
}
