using UnityEngine;

namespace PrehistoricSurvival.Core
{
    /// <summary>
    /// Central registry of every runtime asset the game needs (sprites, prefabs,
    /// databases). It lives at <c>Assets/Resources/GameLibrary.asset</c> and is
    /// generated by the editor tool (PrehistoricSurvival → Setup Entire Project).
    ///
    /// Because it is loaded with <see cref="Resources.Load"/>, systems such as the
    /// runtime bootstrapper and the chunk streamer can build the entire game world
    /// without any hand-wired scene references.
    /// </summary>
    [CreateAssetMenu(fileName = "GameLibrary", menuName = "PrehistoricSurvival/Game Library")]
    public class GameLibrary : ScriptableObject
    {
        public const string ResourcePath = "GameLibrary";

        [Header("Player")]
        public GameObject playerPrefab;

        [Header("Ground Sprites (order: dirt, grass, sand, snow, stone, mud)")]
        public Sprite[] groundSprites = new Sprite[6];
        public Sprite oceanWaterSprite;
        public Sprite shallowWaterSprite;
        public Sprite riverWaterSprite;

        [Header("Vegetation Prefabs")]
        public GameObject[] coldTreePrefabs;      // pine / taiga
        public GameObject[] temperateTreePrefabs; // oak, apple
        public GameObject[] tropicalTreePrefabs;  // fig, apple
        public GameObject[] bushPrefabs;
        public GameObject[] rockPrefabs;

        [Header("Animal Prefabs")]
        public GameObject mammothPrefab;
        public GameObject sabertoothPrefab;
        public GameObject caveBearPrefab;
        public GameObject bisonPrefab;

        [Header("UI")]
        public Sprite healthIcon, hungerIcon, thirstIcon, energyIcon, staminaIcon;
        public Sprite uiCircleSprite;

        [Header("Databases")]
        public ScriptableObject recipeDatabase;

        private static GameLibrary _instance;

        /// <summary>Loads (and caches) the library from Resources. May return null before setup.</summary>
        public static GameLibrary Instance
        {
            get
            {
                if (_instance == null)
                    _instance = Resources.Load<GameLibrary>(ResourcePath);
                return _instance;
            }
        }

        /// <summary>All animal prefabs that are non-null.</summary>
        public GameObject[] AllAnimals()
        {
            var list = new System.Collections.Generic.List<GameObject>(4);
            if (mammothPrefab != null) list.Add(mammothPrefab);
            if (sabertoothPrefab != null) list.Add(sabertoothPrefab);
            if (caveBearPrefab != null) list.Add(caveBearPrefab);
            if (bisonPrefab != null) list.Add(bisonPrefab);
            return list.ToArray();
        }

        /// <summary>Pick a random non-null entry from an array, or null.</summary>
        public static GameObject Pick(GameObject[] array, float random01)
        {
            if (array == null || array.Length == 0) return null;
            int start = Mathf.Clamp(Mathf.FloorToInt(random01 * array.Length), 0, array.Length - 1);
            for (int i = 0; i < array.Length; i++)
            {
                var candidate = array[(start + i) % array.Length];
                if (candidate != null) return candidate;
            }
            return null;
        }
    }
}
