using UnityEngine;

namespace PrehistoricSurvival.Core
{
    /// <summary>
    /// Central registry of every runtime asset the game needs (sprites, prefabs,
    /// databases). It lives at <c>Assets/Resources/GameLibrary.asset</c> and is
    /// generated by the editor tool (PrehistoricSurvival → Setup Entire Project).
    ///
    /// Because it is loaded with <see cref="Resources.Load"/>, systems such as the
    /// runtime bootstrapper and the chunk streamer can build the entire game world
    /// without any hand-wired scene references.
    /// </summary>
    [CreateAssetMenu(fileName = "GameLibrary", menuName = "PrehistoricSurvival/Game Library")]
    public class GameLibrary : ScriptableObject
    {
        public const string ResourcePath = "GameLibrary";

        [Header("Player")]
        public GameObject playerPrefab;

        [Header("Ground Sprites (order: dirt, grass, sand, snow, stone, mud)")]
        public Sprite[] groundSprites = new Sprite[6];
        [Tooltip("3 texture variants per ground type (6 x 3 = 18). Optional – tiles repeat when empty.")]
        public Sprite[] groundVariantSprites;
        public Sprite oceanWaterSprite;
        public Sprite shallowWaterSprite;
        public Sprite riverWaterSprite;
        [Tooltip("Ocean water animation frames (4). Falls back to the static sprite.")]
        public Sprite[] oceanWaterFrames;
        [Tooltip("Shallow/lake water animation frames (4).")]
        public Sprite[] shallowWaterFrames;
        [Tooltip("River water animation frames (4).")]
        public Sprite[] riverWaterFrames;

        [Header("Vegetation Prefabs")]
        public GameObject[] coldTreePrefabs;      // pine / taiga
        public GameObject[] temperateTreePrefabs; // oak, apple
        public GameObject[] tropicalTreePrefabs;  // fig, apple
        public GameObject[] bushPrefabs;
        public GameObject[] rockPrefabs;

        [Header("Animal Prefabs")]
        public GameObject mammothPrefab;
        public GameObject sabertoothPrefab;
        public GameObject caveBearPrefab;
        public GameObject bisonPrefab;
        [Tooltip("Additional species (Dire Wolf, Cave Lion, ...) — names must match AnimalCatalog.")]
        public GameObject[] extraAnimalPrefabs = new GameObject[0];

        /// <summary>Find a species prefab by its catalog prefab name.</summary>
        public GameObject AnimalPrefab(string prefabName)
        {
            switch (prefabName)
            {
                case "Mammoth": return mammothPrefab;
                case "Sabertooth": return sabertoothPrefab;
                case "CaveBear": return caveBearPrefab;
                case "Bison": return bisonPrefab;
            }
            if (extraAnimalPrefabs != null)
                foreach (var p in extraAnimalPrefabs)
                    if (p != null && p.name == prefabName) return p;
            return null;
        }

        [Header("UI")]
        public Sprite healthIcon, hungerIcon, thirstIcon, energyIcon, staminaIcon;
        public Sprite uiCircleSprite;

        [Header("Audio")]
        public AudioLibrary audioLibrary;

        [Header("Databases")]
        public ScriptableObject recipeDatabase;

        private static GameLibrary _instance;

        /// <summary>Loads (and caches) the library from Resources. May return null before setup.</summary>
        public static GameLibrary Instance
        {
            get
            {
                if (_instance == null)
                {
                    _instance = Resources.Load<GameLibrary>(ResourcePath);
                    if (_instance != null) _instance.ResolveRuntimeSprites();
                }
                return _instance;
            }
        }

        private static readonly string[] GroundNames = { "dirt", "grass", "sand", "snow", "stone", "mud" };

        /// <summary>
        /// Safety net for library assets generated before the realistic art pass:
        /// fills missing ground/water sprite references from the mirrored copies in
        /// Resources/Sprites/Tiles so terrain and animated water always render.
        /// </summary>
        private void ResolveRuntimeSprites()
        {
            for (int i = 0; i < GroundNames.Length; i++)
            {
                if (groundSprites == null) groundSprites = new Sprite[6];
                if (i < groundSprites.Length && groundSprites[i] == null)
                    groundSprites[i] = Resources.Load<Sprite>($"Sprites/Tiles/{GroundNames[i]}_tile_0");
            }
            if ((groundVariantSprites == null || groundVariantSprites.Length < 18) ||
                System.Array.IndexOf(groundVariantSprites ?? new Sprite[0], null) >= 0)
            {
                var variants = new Sprite[18];
                bool any = false;
                for (int g = 0; g < 6; g++)
                    for (int v = 0; v < 3; v++)
                    {
                        variants[g * 3 + v] = Resources.Load<Sprite>($"Sprites/Tiles/{GroundNames[g]}_tile_{v}");
                        if (variants[g * 3 + v] != null) any = true;
                    }
                if (any) groundVariantSprites = variants;
            }
            oceanWaterSprite = ResolveWater(oceanWaterSprite, ref oceanWaterFrames, "ocean_water");
            shallowWaterSprite = ResolveWater(shallowWaterSprite, ref shallowWaterFrames, "calm_water");
            riverWaterSprite = ResolveWater(riverWaterSprite, ref riverWaterFrames, "river_water");
        }

        private Sprite ResolveWater(Sprite fallback, ref Sprite[] frames, string name)
        {
            if (frames == null || frames.Length < 4 || System.Array.IndexOf(frames, null) >= 0)
            {
                var loaded = new Sprite[4];
                bool any = false;
                for (int f = 0; f < 4; f++)
                {
                    loaded[f] = Resources.Load<Sprite>($"Sprites/Tiles/{name}_tile_{f}");
                    if (loaded[f] != null) any = true;
                }
                if (any) frames = loaded;
            }
            if (frames != null)
            {
                foreach (var f in frames) if (f != null) return f;
            }
            return fallback;
        }

        /// <summary>All animal prefabs that are non-null.</summary>
        public GameObject[] AllAnimals()
        {
            var list = new System.Collections.Generic.List<GameObject>(4);
            if (mammothPrefab != null) list.Add(mammothPrefab);
            if (sabertoothPrefab != null) list.Add(sabertoothPrefab);
            if (caveBearPrefab != null) list.Add(caveBearPrefab);
            if (bisonPrefab != null) list.Add(bisonPrefab);
            return list.ToArray();
        }

        /// <summary>Pick a random non-null entry from an array, or null.</summary>
        public static GameObject Pick(GameObject[] array, float random01)
        {
            if (array == null || array.Length == 0) return null;
            int start = Mathf.Clamp(Mathf.FloorToInt(random01 * array.Length), 0, array.Length - 1);
            for (int i = 0; i < array.Length; i++)
            {
                var candidate = array[(start + i) % array.Length];
                if (candidate != null) return candidate;
            }
            return null;
        }
    }
}
